// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>

void motorSpeedCB(lv_event_t *e)
{
	lv_obj_t *slider = lv_event_get_target(e);
	int value = (int)lv_slider_get_value(slider); // 0 ~ 100 (%)

	printf("******************\n");
}

void ledSwitchCB(lv_event_t *e)
{
	// Your code here
	lv_obj_t *sw = lv_event_get_target(e);
	bool isOn = lv_obj_has_state(sw, LV_STATE_CHECKED);
	printf("------------------\n");
}