// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_LedSwitch;
extern lv_obj_t * ui_Panel1;
extern void ui_event_SpeedBar(lv_event_t * e);
extern void ui_event_LedSwitch(lv_event_t * e);
extern lv_obj_t * ui_SpeedBar;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ledSwitch;
extern lv_obj_t * uic_speed_bar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

