// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_speed_bar;
lv_obj_t * uic_ledSwitch;
lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_LedSwitch = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_SpeedBar = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
// event funtions
void ui_event_SpeedBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        motorSpeedCB(e);
    }
}


// event funtions
void ui_event_LedSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ledSwitchCB(e);
    }
}


// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -86);
    lv_obj_set_y(ui_Label3, -135);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "전등");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_NanumBrush, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button2, 54);
    lv_obj_set_height(ui_Button2, 41);
    lv_obj_set_x(ui_Button2, -52);
    lv_obj_set_y(ui_Button2, -13);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LedSwitch = lv_switch_create(ui_MainScreen);
    lv_obj_set_width(ui_LedSwitch, 50);
    lv_obj_set_height(ui_LedSwitch, 25);
    lv_obj_set_x(ui_LedSwitch, -41);
    lv_obj_set_y(ui_LedSwitch, -135);
    lv_obj_set_align(ui_LedSwitch, LV_ALIGN_CENTER);

    ui_Panel1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel1, 207);
    lv_obj_set_height(ui_Panel1, 53);
    lv_obj_set_x(ui_Panel1, -2);
    lv_obj_set_y(ui_Panel1, -86);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpeedBar = lv_slider_create(ui_Panel1);
    lv_slider_set_value(ui_SpeedBar, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SpeedBar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SpeedBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBar, 150);
    lv_obj_set_height(ui_SpeedBar, 10);
    lv_obj_set_x(ui_SpeedBar, 11);
    lv_obj_set_y(ui_SpeedBar, 8);
    lv_obj_set_align(ui_SpeedBar, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -3);
    lv_obj_set_y(ui_Label1, -16);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "모터속도 제어");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_NanumBrush, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_MainScreen, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, -6);
    lv_obj_set_y(ui_Spinner1, 99);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_add_event_cb(ui_SpeedBar, ui_event_SpeedBar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LedSwitch, ui_event_LedSwitch, LV_EVENT_ALL, NULL);
    uic_ledSwitch = ui_LedSwitch;
    uic_speed_bar = ui_SpeedBar;

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_Label3 = NULL;
    ui_Button2 = NULL;
    uic_ledSwitch = NULL;
    ui_LedSwitch = NULL;
    ui_Panel1 = NULL;
    uic_speed_bar = NULL;
    ui_SpeedBar = NULL;
    ui_Label1 = NULL;
    ui_Spinner1 = NULL;

}
